package com.iwhaleai.byai.framework.core.liveness;

import com.iwhaleai.byai.framework.common.Constants;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Cross-SDK contract tests for the wait-index member codec and shard function.
 *
 * <p><b>These assert reference values produced by the Python implementation, not
 * round-trips.</b> Encoding with our own encoder and decoding with our own decoder
 * always agrees with itself, so a round-trip cannot detect the one failure that
 * matters here: computing a different member or shard than the other SDKs, which
 * makes cross-language chains stop seeing each other's entries with no error.
 *
 * <p>Reference values were generated by running the Python algorithm directly.
 */
class WaitIndexTest {

    // --- shard function (contract section 3) --------------------------------

    @Test
    void fnv1a32MatchesThePythonReferenceVectors() {
        assertEquals(1532043137L, WaitIndex.fnv1a32("sess-1"));
        assertEquals(1481710280L, WaitIndex.fnv1a32("sess-2"));
        assertEquals(2166136261L, WaitIndex.fnv1a32(""));
        assertEquals(3826002220L, WaitIndex.fnv1a32("a"));
        assertEquals(3888157041L, WaitIndex.fnv1a32("sess|pipe"));
        assertEquals(1275451802L, WaitIndex.fnv1a32("sess\\back"));
        // Non-ASCII: the hash is over UTF-8 bytes, not chars.
        assertEquals(3489774755L, WaitIndex.fnv1a32("用户会话"));
    }

    @Test
    void shardMatchesThePythonReferenceVectors() {
        // The contract names this one explicitly.
        assertEquals(1, WaitIndex.shardForSession("sess-1"));
        assertEquals(8, WaitIndex.shardForSession("sess-2"));
        assertEquals(5, WaitIndex.shardForSession(""));
        assertEquals(12, WaitIndex.shardForSession("a"));
        assertEquals(1, WaitIndex.shardForSession("sess|pipe"));
        assertEquals(10, WaitIndex.shardForSession("sess\\back"));
        assertEquals(3, WaitIndex.shardForSession("用户会话"));
    }

    @Test
    void theShardIsNotStringHashCode() {
        // Guards the single most likely porting mistake. String.hashCode() is a
        // different algorithm, and using it would send Java to a different shard
        // than the Python or TS worker that registered the wait.
        assertNotEquals(
                Math.floorMod("sess-1".hashCode(), Constants.WAIT_INDEX_SHARDS),
                WaitIndex.shardForSession("sess-1"));
    }

    @Test
    void everyShardIsWithinRange() {
        for (int i = 0; i < 200; i++) {
            int shard = WaitIndex.shardForSession("session-" + i);
            assertTrue(shard >= 0 && shard < Constants.WAIT_INDEX_SHARDS,
                    "shard out of range for session-" + i + ": " + shard);
        }
    }

    // --- member encoding (contract section 2) -------------------------------

    @Test
    void encodesToThePythonReferenceStrings() {
        assertEquals("sess-1|msg-a|msg-b|tg-1",
                WaitIndex.encodeMember("sess-1", "msg-a", "msg-b", "tg-1"));
        // Escaping: backslash first, then pipe.
        assertEquals("a\\|b|c\\\\d||",
                WaitIndex.encodeMember("a|b", "c\\d", "", ""));
        assertEquals("sess-1|msg-a||",
                WaitIndex.encodeMember("sess-1", "msg-a", "", ""));
    }

    @Test
    void decodesThePythonReferenceStrings() {
        WaitIndex.Member m = WaitIndex.decodeMember("a\\|b|c\\\\d||");
        assertEquals("a|b", m.sessionId());
        assertEquals("c\\d", m.parentMessageId());
        assertEquals("", m.childMessageId());
        assertEquals("", m.taskGroupId());
    }

    @Test
    void roundTripsAFieldContainingBothSpecialCharacters() {
        // A separator inside a field is what a naive split() would cut in half.
        String nasty = "sess|with\\both";
        WaitIndex.Member m = WaitIndex.decodeMember(
                WaitIndex.encodeMember(nasty, "msg|a", "msg\\b", "tg-1"));
        assertEquals(nasty, m.sessionId());
        assertEquals("msg|a", m.parentMessageId());
        assertEquals("msg\\b", m.childMessageId());
        assertEquals("tg-1", m.taskGroupId());
    }

    @Test
    void nullFieldsEncodeAsEmpty() {
        assertEquals("|||", WaitIndex.encodeMember(null, null, null, null));
    }

    @Test
    void aDanglingEscapeIsRejected() {
        assertThrows(IllegalArgumentException.class,
                () -> WaitIndex.decodeMember("sess|msg|child|tg\\"));
    }

    @Test
    void aWrongFieldCountIsRejected() {
        assertThrows(IllegalArgumentException.class,
                () -> WaitIndex.decodeMember("only|three|fields"));
        assertThrows(IllegalArgumentException.class,
                () -> WaitIndex.decodeMember("a|b|c|d|e"));
    }
}
